- name: Enable password autentication 
  replace: 
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
    backup: yes

- name: Append RSA authentication 
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "RSAAuthentication yes"

#- name: Debug groups
#  debug: var=groups

#- name: Debug hostsvars
#  debug: var=hostvars

- name: Erase everything from /etc/hosts
  shell: "cat /dev/null > /etc/hosts"

- name: Append master to etc/hosts
  lineinfile:
    path: /etc/hosts
    create: yes
    state: present
    line: "{{ item }}\tmaster"
  with_items: "{{ master_ip }}"

- name: Append slaves to etc/hosts
  lineinfile:
    path: /etc/hosts
    create: yes
    state: present
    line: "{{ item }}\tslave{{my_idx|int+1}}"
  with_sequence: start="{{ initial_ip }}" end="{{ latest_ip }}" stride=1 format="{{ group_ip }}%d"
  loop_control:
    index_var: my_idx

- name: Append ssh public key
  lineinfile:
    path: "/home/{{ user }}/.ssh/authorized_keys"
    create: yes
    state: present
    line: "{{ hostvars['master_node']['public_key']['stdout'] }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
