#!/bin/bash
export HADOOP_COMMON_HOME=/usr/lib/hadoop
export HADOOP_MAPERED_HOME=$HADOOP_COMMON_HOME
export HADOOP_HDFS_HOME=$HADOOP_COMMON_HOME
export YARN_HADOOP=$HADOOP_COMMON_HOME
export HADOOP_PREFIX=$HADOOP_COMMON_HOME
export PATH=$PATH:$HADOOP_COMMON_HOME/bin:$HADOOP_COMMON_HOME/sbin
