---
- hosts: all
  become: true
  roles:
  - basic

- hosts: master
  become: true
  roles:
  - master
- hosts: slave
  become: true
  roles:
  - slave

-------------------
- name: "Install Java"

- name: "Create Hadoop directory"
  file: path=/usr/lib/hadoop state directory owner:nobody group:nogroup mode:0755
- name; "Copying Hadoop srcs"
  copy: src=/hadoop.tar.gz dest=/usr/lib/hadoop/hadoop.tar.gz owner:nobody group:nogroup mode:0755
- name: "Adding ip in the /etc/hosts file"
  lineinfile: name=/etc/hosts line="{{ hostvars['ipaddr'] }}slave"
