---
# Basic provisioning example
- name: Create an EC2 instance
  ec2:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    key_name: "{{key_name}}"
    region: "{{aws_region}}"
    vpc_subnet_id: "{{vpc_id}}"
    group_id: "{{group_id}}"
    instance_type: "{{instance_type}}"
    image: "{{ami_id}}"
    wait: yes
    volumes:
    - device_name: "{{volumes.device_name}}"
      volume_type: "{{volumes.volume_type}}"
      volume_size: "{{volumes.volume_size}}"
    exact_count: 1
    count_tag:
       Name: aws-demo
    instance_tags:
       Name: aws-demo
  register: ec2
