- name: Generate SSH keys
  shell: sudo -u {{ user }} ssh-keygen -t rsa -f /home/{{ user }}/.ssh/id_rsa -q -N ""
  args:
    creates: "/home/{{ user }}/.ssh/id_rsa"

- name: Public key
  shell: "cat /home/{{ user }}/.ssh/id_rsa.pub"
  register: public_key

- name: Disable hostkey verification for master node
  blockinfile:
    path: "/home/{{ user }}/.ssh/config"
    block: |
      Host *
        StrictHostKeyChecking no
    owner: "{{ user }}"
    group: "{{ user }}"
    create: yes
    mode: 0400

- name: Copying lib artifacts
  copy:
    src: lib
    dest: "/home/{{ user }}/"
    owner: root
    group: root
    mode: 0777

- name: Copying util executable files and process
  copy:
    src: util/
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: +x

- name: Copying util executable files and process
  copy:
    src: wordcount-hadoop-1.0-SNAPSHOT.jar
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"

#- debug: var=public_key

- set_fact:
     public_key: "{{ public_key }}"
